[phases.setup]
nixPkgs = ['python311', 'chromium']

[phases.install]
cmds = [
  'pip install --upgrade pip',
  'pip install -r requirements.txt',
  'playwright install chromium'
]

[start]
cmd = 'gunicorn app:app --host 0.0.0.0 --port $PORT'