services:
  - type: web
    name: flesk-ai-overview
    env: python
    plan: free
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: source venv/bin/activate && gunicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GEMINI_API_KEY
        sync: false
    healthCheckPath: /
    autoDeploy: true
    branch: main