services:
  - type: web
    name: flesk-ai-overview
    env: python
    plan: free
    buildCommand: python -m pip install --upgrade pip && python -m pip install setuptools==68.2.2 wheel==0.41.2 --no-deps && python -m pip install -r requirements.txt --no-build-isolation && playwright install chromium
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: GEMINI_API_KEY
        sync: false
    healthCheckPath: /
    autoDeploy: true
    branch: main