name: flesk-ai-overview
services:
- name: web
  source_dir: /
  github:
    repo: your-username/Flesk-Ai-Overview
    branch: main
    deploy_on_push: true
  run_command: gunicorn --bind 0.0.0.0:8080 app:app
  environment_slug: docker
  instance_count: 1
  instance_size_slug: basic-xxs
  dockerfile_path: Dockerfile
  http_port: 8080
  envs:
  - key: GEMINI_API_KEY
    scope: RUN_TIME
    type: SECRET
  - key: PYTHONUNBUFFERED
    value: "1"
    scope: RUN_TIME
  - key: DISPLAY
    value: ":99"
    scope: RUN_TIME
  health_check:
    http_path: /
  routes:
  - path: /
    preserve_path_prefix: true

static_sites: []
databases: []
jobs: []
workers: []